export type BatchPosterThemeCluster = {
  id: number;
  name: string;
  core_anchor: string;
  broad_concept: string;
  allowed_entities: string[];
  interaction_required?: boolean;
  market_insight?: string;
  interaction_blueprint?: string;
};

export const BATCH_POSTER_THEME_CLUSTERS: BatchPosterThemeCluster[] = [
  {
    id: 1,
    name: "古埃及墓室",
    core_anchor: "Egyptian Tomb Explorer",
    broad_concept: "Ancient Nile Empire Relics & Burial Vaults",
    allowed_entities: ["Pharaoh Tomb Raider", "Anubis High Priest", "Cleopatra Queen", "Scarab Guardian", "Golden Sarcophagus Keeper"],
  },
  {
    id: 2,
    name: "深海沉船宝藏",
    core_anchor: "Sunken Pirate Galleon",
    broad_concept: "Undersea Wreck Treasures & Abyssal Divers",
    allowed_entities: ["Deep Sea Diver", "Ghost Pirate Captain", "Giant Octopus", "Coral Treasure Chest", "Anchor Chain Salvager"],
    interaction_required: true,
  },
  {
    id: 3,
    name: "西部沙龙赌客",
    core_anchor: "Wild West Saloon Gambler",
    broad_concept: "Wild West Frontier Fortune & Saloon High Stakes",
    allowed_entities: ["Cowboy Gambler", "Poker Dealer", "Gold Rush Miner", "Rodeo Rider", "Sheriff Badge Collector"],
    interaction_required: true,
  },
  {
    id: 4,
    name: "维京长船战士",
    core_anchor: "Norse Viking Warrior",
    broad_concept: "Norse Raiding Legends & Storm Sea Hoards",
    allowed_entities: ["Viking Berserker", "Shield Maiden", "Longship Captain", "Rune Seer", "Dragon Prow Raider"],
  },
  {
    id: 5,
    name: "热带丛林神庙",
    core_anchor: "Jungle Temple Adventurer",
    broad_concept: "Lost Jungle Civilizations & Emerald Ruins",
    allowed_entities: ["Temple Explorer", "Jaguar Guardian", "Stone Idol Priest", "Emerald Serpent Totem", "Mossy Ruin Scout"],
    interaction_required: true,
  },
  {
    id: 6,
    name: "蒸汽朋克飞艇",
    core_anchor: "Steampunk Airship Captain",
    broad_concept: "Victorian Sky Empire & Brass Air Fleets",
    allowed_entities: ["Airship Captain", "Brass Automaton", "Gear Tinkerer", "Sky Pirate", "Clockwork Navigator"],
  },
  {
    id: 7,
    name: "中世纪皇家宴会",
    core_anchor: "Medieval Royal Feast",
    broad_concept: "Medieval Court Banquets & Noble Tribute Halls",
    allowed_entities: ["Noble Queen", "Knight Champion", "Royal Chef", "Court Jester", "Herald Trumpeter"],
  },
  {
    id: 8,
    name: "阿兹特克金字塔",
    core_anchor: "Aztec Pyramid Priest",
    broad_concept: "Mesoamerican Sun Rituals & Obsidian Temples",
    allowed_entities: ["Sun Priest", "Eagle Warrior", "Jade Skull Guardian", "Obsidian Champion", "Feathered Serpent Avatar"],
  },
  {
    id: 9,
    name: "北极冰洞探险",
    core_anchor: "Arctic Ice Cave Explorer",
    broad_concept: "Polar Expedition Vaults & Aurora Ice Realms",
    allowed_entities: ["Ice Spelunker", "Polar Bear Guardian", "Aurora Hunter", "Frozen Mammoth Tusk Seeker", "Crystal Miner"],
  },
  {
    id: 10,
    name: "加勒比海盗",
    core_anchor: "Caribbean Pirate Captain",
    broad_concept: "Caribbean Sea Raiders & Cannon Deck Fortunes",
    allowed_entities: ["Pirate Captain", "Cannon Master", "Treasure Quartermaster", "Parrot Lookout", "Skeleton Crew Mate"],
  },
  {
    id: 11,
    name: "中式宫廷庭院",
    core_anchor: "Chinese Palace Scholar",
    broad_concept: "Imperial Eastern Court & Jade Seal Courts",
    allowed_entities: ["Palace Scholar", "Empress Consort", "Jade Seal Official", "Lantern Maiden", "Dragon Throne Guard"],
  },
  {
    id: 12,
    name: "非洲 Safari / 狮与钻石",
    core_anchor: "Lion Guardians",
    broad_concept: "African Savannah Apex Predators & Diamond Vaults",
    allowed_entities: ["Majestic Lion", "Black Rhino", "Cheetah Hunter", "Elephant Matriarch", "Leopard Stalker"],
    interaction_required: true,
  },
  {
    id: 13,
    name: "维多利亚鬼屋",
    core_anchor: "Haunted Victorian Mansion",
    broad_concept: "Gothic Estate Mysteries & Cursed Antiques",
    allowed_entities: ["Ghostly Hostess", "Antique Collector", "Phantom Butler", "Séance Medium", "Cursed Heir"],
  },
  {
    id: 14,
    name: "复古太空站赌场",
    core_anchor: "Retro Space Station Casino",
    broad_concept: "Retro Sci-Fi Gambling Orbit & Alien Jackpots",
    allowed_entities: ["Alien Dealer", "Robot Croupier", "Cosmic Captain", "Zero-G Gambler", "Star Chip Hoarder"],
  },
  {
    id: 15,
    name: "糖果高糖乐园",
    core_anchor: "High-Sugar Candy Paradise",
    broad_concept: "Fantasy Treat Worlds & Sweet Treasure Kingdoms",
    allowed_entities: ["Gummy Bear King", "Lollipop Wizard", "Cupcake Queen", "Jellybean Dragon", "Marshmallow Knight"],
  },
  {
    id: 16,
    name: "户外捕鱼 & 深海",
    core_anchor: "Fishing Captain / Bass",
    broad_concept: "Deep Sea Catch & Marine Monsters",
    allowed_entities: ["Experienced Fishing Captain", "Giant Marlin", "Great White Shark", "Kraken Squid", "King Crab"],
    interaction_required: true,
  },
  {
    id: 17,
    name: "暗黑硬核西部",
    core_anchor: "Gritty Wild West Outlaw",
    broad_concept: "Gritty Frontier Violence & Volatile Gold Runs",
    allowed_entities: ["Desperado Outlaw", "Bounty Hunter", "Snake Oil Bandit", "Dynamite Saboteur", "Dusty Gunslinger"],
    interaction_required: true,
  },
  {
    id: 18,
    name: "旷野猛兽",
    core_anchor: "Buffalo & Wolf",
    broad_concept: "North American Wilderness Apex Creatures",
    allowed_entities: ["Mighty Buffalo", "Timber Wolf", "Grizzly Bear", "Bald Eagle", "Mountain Cougar"],
    interaction_required: true,
  },
  {
    id: 19,
    name: "天神 & 古帝国神话",
    core_anchor: "Ancient Pantheon Gods",
    broad_concept: "Mythic Ancient Empires & Divine Relic Thrones",
    allowed_entities: ["Zeus Thunder King", "Ra Sun God", "Odin All-Father", "Athena War Sage", "Anubis Judge"],
  },
  {
    id: 20,
    name: "复古霓虹水果机",
    core_anchor: "Classic 7s Fruit Machine",
    broad_concept: "Retro Arcade Jackpot Icons & Lucky Reel Symbols",
    allowed_entities: ["Lucky Seven Mascot", "Cherry Bell Spinner", "Bar Symbol King", "Diamond Jackpot Genie", "Slot Lever Master"],
  },
  {
    id: 21,
    name: "地下淘金热",
    core_anchor: "Gold-Mining Dwarves",
    broad_concept: "Underground Gold Rush & Torch-Lit Mine Vaults",
    allowed_entities: ["Dwarf Foreman", "Pickaxe Miner", "Gem Prospector", "Mine Cart Boss", "Crystal Vein Hunter"],
  },
  {
    id: 22,
    name: "墨西哥亡灵节",
    core_anchor: "Dia de los Muertos Carnival",
    broad_concept: "Mexican Festival of Souls & Marigold Altars",
    allowed_entities: ["Sugar Skull Dancer", "Marigold Queen", "Skeleton Musician", "Festival Mariachi", "Ofrenda Matriarch"],
  },
  {
    id: 23,
    name: "终极金库大劫案",
    core_anchor: "High-Tech Bank Vault Heist",
    broad_concept: "High-Tech Vault Robbery & Laser Grid Treasuries",
    allowed_entities: ["Vault Hacker", "Safecracker Lead", "Laser Grid Dodger", "Cash Bag Bandit", "Security Override Thief"],
    interaction_required: true,
  },
  {
    id: 24,
    name: "魔幻女巫药水坊",
    core_anchor: "Witchcraft Magic Potions",
    broad_concept: "Arcane Alchemy Workshops & Enchanted Brew Labs",
    allowed_entities: ["Potion Witch", "Spell Brewer", "Crystal Oracle", "Familiar Cat Sorceress", "Herb Gatherer Sage"],
  },
  {
    id: 25,
    name: "末日废土摇滚",
    core_anchor: "Apocalypse Undead Rock Band",
    broad_concept: "Apocalypse Music Rebels & Rust Stage Fortunes",
    allowed_entities: ["Zombie Guitarist", "Undead Drummer", "Wasteland Vocalist", "Flaming Bass Player", "Rust Stage Roadie"],
  },
  {
    id: 26,
    name: "雍容华贵宫廷牡丹",
    core_anchor: "Imperial Peony Court",
    broad_concept: "Eastern Imperial Garden Nobility & Silk Court Rituals",
    allowed_entities: ["Peony Empress", "Silk-Robed Noble Lady", "Jade Hairpin Courtier", "Garden Poet Scholar", "Incense Bearer Maiden"],
  },
  {
    id: 27,
    name: "地下赛车",
    core_anchor: "Underground Street Racing",
    broad_concept: "Underground Nitro Showdowns & Trophy Cash Runs",
    allowed_entities: ["Muscle Car Racer", "Drag Strip Queen", "Nitro Mechanic", "Trophy Biker", "Underglow Champion"],
  },
  {
    id: 28,
    name: "日式武士城宝库",
    core_anchor: "Samurai Castle Treasury",
    broad_concept: "Feudal Japanese Warlords & Katana Vault Halls",
    allowed_entities: ["Samurai Daimyo", "Ronin Warrior", "Katana Master", "Archer Retainer", "Treasure Chamber Guard"],
  },
  {
    id: 29,
    name: "爱尔兰神话 / 金罐",
    core_anchor: "Pot of Gold / Leprechaun",
    broad_concept: "Celtic Mythic Hillside Fortune & Rainbow Relics",
    allowed_entities: ["Leprechaun Trickster", "Rainbow Arch Guardian", "Clover Field Spirit", "Celtic Bard", "Gold Cauldron Keeper"],
  },
  {
    id: 30,
    name: "罗马竞技场冠军",
    core_anchor: "Roman Colosseum Champion",
    broad_concept: "Imperial Gladiator Glory & Arena Tribute Chests",
    allowed_entities: ["Gladiator Champion", "Lion Tamer Fighter", "Laurel Crown Victor", "Arena Beast Hunter", "Tribute Champion"],
    interaction_required: true,
  },
  {
    id: 31,
    name: "夏威夷火山女神",
    core_anchor: "Hawaiian Volcano Goddess",
    broad_concept: "Polynesian Fire Shrine Rituals & Lava Gem Offerings",
    allowed_entities: ["Volcano Goddess", "Tiki Guardian", "Lava Dancer", "Fire Gem Priest", "Island Warrior Chief"],
  },
  {
    id: 32,
    name: "赛博朋克霓虹巷",
    core_anchor: "Neon Cyberpunk Hacker",
    broad_concept: "Neon Megacity Jackpots & Holographic Heists",
    allowed_entities: ["Hologram Hacker", "Chrome Drone Pilot", "Neon Alley Runner", "Jackpot Courier", "Data Heist Phantom"],
  },
  {
    id: 33,
    name: "阿拉伯沙漠宫殿",
    core_anchor: "Arabian Desert Palace Merchant",
    broad_concept: "Arabian Silk Palace Trade & Jewel-Filled Caravans",
    allowed_entities: ["Palace Merchant", "Lamp Genie Host", "Carpet Rider", "Jewel Trader", "Oasis Caravan Leader"],
  },
  {
    id: 34,
    name: "亚马逊雨林萨满",
    core_anchor: "Amazon Rainforest Shaman",
    broad_concept: "Amazon Jungle Spirit Realms & Gold Idol Sanctuaries",
    allowed_entities: ["Rainforest Shaman", "Gold Idol Guardian", "Exotic Bird Totem", "Root Healer", "Jaguar Spirit Caller"],
    interaction_required: true,
  },
  {
    id: 35,
    name: "希腊冥界渡船",
    core_anchor: "Greek Underworld Ferry",
    broad_concept: "Greek Mythic Afterlife Passage & Coin River Gates",
    allowed_entities: ["Ferry Soul Guide", "Coin River Guardian", "Gate Keeper Shade", "Mythic Gate Sentinel", "Underworld Traveler"],
    interaction_required: true,
  },
  {
    id: 36,
    name: "史前洞穴 / 猛犸象牙",
    core_anchor: "Prehistoric Cave Painter / Mammoth",
    broad_concept: "Prehistoric Ice Age Hunters & Tribal Treasure Caves",
    allowed_entities: ["Cave Painter Shaman", "Mammoth Hunt Leader", "Saber Tooth Tracker", "Amber Gem Gatherer", "Tribal Treasure Keeper"],
    interaction_required: true,
  },
  {
    id: 37,
    name: "1930美式橡皮管动画",
    core_anchor: "Rubber-Hose Cartoon Mascot",
    broad_concept: "1930s Toon Slot Carnival & Bouncing Reel Mascots",
    allowed_entities: ["Bouncing Toon Mascot", "Spring-Limbed Joker", "Whistle Steam Robot", "Coin-Eyed Cat", "Jackpot Jack-in-the-Box"],
  },
  {
    id: 38,
    name: "波普艺术老式小丑",
    core_anchor: "Vintage Pop-Art Joker",
    broad_concept: "Vintage Lucky Bell Icons & Classic Slot Symbols",
    allowed_entities: ["Pop-Art Joker", "Lucky Bell Ringmaster", "Starburst Jackpot Sprite", "Cherry Crown Fool", "Classic Bar Mascot"],
  },
  {
    id: 39,
    name: "老牌好莱坞爵士夜总会",
    core_anchor: "Golden-Age Hollywood Jazz Lounge",
    broad_concept: "Golden Age Casino Glamour & Art-Deco Show Floors",
    allowed_entities: ["Feather Showgirl", "Jazz Singer Star", "Art-Deco Croupier", "Champagne High Roller", "Velvet Lounge Host"],
  },
  {
    id: 40,
    name: "克苏鲁深渊巨兽",
    core_anchor: "Cthulhu Deep Leviathan",
    broad_concept: "Deep Abyss Cosmic Horrors & Tentacle Guarded Hoards",
    allowed_entities: ["Abyss Leviathan", "Tentacle Throne Beast", "Sunken Cult Priest", "Deep Sea Kraken Spawn", "Coral Tomb Watcher"],
    interaction_required: true,
  },
  {
    id: 41,
    name: "北欧尘世巨蟒",
    core_anchor: "Jormungandr World Serpent",
    broad_concept: "Norse World Serpent Myths & Storm Sea Hoards",
    allowed_entities: ["World Serpent Jormungandr", "Storm Sea Raider", "Rune Stone Guardian", "Mythic Hoard Keeper", "Serpent Coiled Titan"],
    interaction_required: true,
  },
  {
    id: 42,
    name: "30年代芝加哥黑手党",
    core_anchor: "1930s Chicago Mafia Boss",
    broad_concept: "1930s Speakeasy Crime Empire & Bullet-Ridden Fortunes",
    allowed_entities: ["Speakeasy Boss", "Tommy Gun Enforcer", "Bourbon Smuggler", "Bulletproof Accountant", "Flapper Informant"],
  },
  {
    id: 43,
    name: "希腊美杜莎神庙",
    core_anchor: "Gorgon Medusa Temple",
    broad_concept: "Greek Cursed Relic Sanctums & Serpent Column Halls",
    allowed_entities: ["Gorgon Medusa", "Serpent Column Priestess", "Stone Statue Hunter", "Cursed Relic Seeker", "Temple Curse Breaker"],
    interaction_required: true,
  },
  {
    id: 44,
    name: "外星飞碟疯狂绑架",
    core_anchor: "Alien UFO Cow Abduction",
    broad_concept: "Extraterrestrial Jackpot Chaos & Tractor Beam Fields",
    allowed_entities: ["UFO Abductor Captain", "Cow Beam Pilot", "Crop Circle Scout", "Alien Jackpot Pod Master", "Tractor Beam Operator"],
    interaction_required: true,
  },
  {
    id: 45,
    name: "吴哥窟失落宝藏",
    core_anchor: "Angkor Wat Lost Gold",
    broad_concept: "Lost Southeast Asian Temple Gold & Jungle Shrine Guardians",
    allowed_entities: ["Stone Guardian Statue", "Jungle Vine Explorer", "Sunlit Shrine Keeper", "Lost Gold Relic Hunter", "Ancient Temple Monk"],
  },
  {
    id: 46,
    name: "三只招财蟾蜍",
    core_anchor: "Three Lucky Fortune Toads",
    broad_concept: "3 Dancing Monkeys Style Fortune Toad Trio & Square-Hole Gold Coin Ponds",
    allowed_entities: ["Emerald Fortune Toad Trio", "Golden Lotus Leaf Platform", "Square-Hole Copper Coin Pile", "Mystic Temple Pond Keeper", "Red Lantern Garden Spirit"],
  },
  {
    id: 47,
    name: "疯狂金猪存钱罐",
    core_anchor: "Smash the Piggy Bank",
    broad_concept: "Piggy Blitz Cash Tornado & Diamond Crown Savings Vaults",
    allowed_entities: ["Diamond Crown Piggy Bank", "Green Cash Bundle Mountain", "Golden Jeweler Hammer", "Steel Vault Gold Bar Keeper", "Office Desk Coin Scatterer"],
  },
  {
    id: 48,
    name: "华尔街金钱帝国",
    core_anchor: "Wall Street Billionaire",
    broad_concept: "Monopoly Slots Tycoon Empire & Black-Gold VIP Bank Fortunes",
    allowed_entities: ["Silver-Haired Billionaire Tycoon", "Penthouse Skyline Mogul", "Black Briefcase Gold Bullion", "Premium Casino Chip Stack", "Private Rooftop Whiskey Baron"],
  },
  {
    id: 49,
    name: "皇家金库大盗",
    core_anchor: "Royal Diamond Heist",
    broad_concept: "Action Jack Museum Heist & Velvet Vault Gem Hoards",
    allowed_entities: ["Monocle Gentleman Thief", "Glowing Blue Diamond Grabber", "Velvet Ruby Display Case", "Royal Gold Coin Sack Spiller", "Deactivated Laser Grid Infiltrator"],
  },
  {
    id: 50,
    name: "翡翠功夫熊猫宝库",
    core_anchor: "Kung Fu Panda Jade Treasury",
    broad_concept: "Fat Panda Mountain Cave & Bamboo-Pattern Gold Scroll Vaults",
    allowed_entities: ["Red Vest Kung Fu Panda", "Translucent Jade Carving Stack", "Bamboo Leaf Gold Coin Altar", "Mountain Cave Waterfall Guardian", "Ancient Golden Scroll Keeper"],
  },
  {
    id: 51,
    name: "财神爷爆裂金元宝",
    core_anchor: "Caishen God of Wealth",
    broad_concept: "Caishen Gold Fortune Wheel & Overflowing Ingots Cornucopia",
    allowed_entities: ["Scarlet Robe God of Wealth", "Glowing Golden Ingot Bearer", "Rotating Jade Fortune Wheel", "Overflowing Golden Cauldron", "Red Envelope Treasure Spiller"],
  },
  {
    id: 52,
    name: "海王波塞冬亚特兰蒂斯",
    core_anchor: "Poseidon Ocean Kingdom",
    broad_concept: "Release the Kraken Sea Throne & Atlantean Trident Pearl Hoards",
    allowed_entities: ["Coral-Crowned Sea God Poseidon", "Glowing Golden Trident Wielder", "Giant Clam Pearl Cluster", "Ancient Greek Coin Sand Pile", "Marble Underwater Throne Guardian"],
    interaction_required: true,
  },
  {
    id: 53,
    name: "亚瑟王与圣杯传奇",
    core_anchor: "King Arthur Excalibur",
    broad_concept: "Avalon Round Table Legend & Holy Grail Knight Gold",
    allowed_entities: ["Silver Plate King Arthur", "Excalibur Stone Sword Griper", "Round Table Gold Coin Scatter", "Holy Grail Chalice Keeper", "Gem-Encrusted Shield Knight"],
    interaction_required: true,
  },
  {
    id: 54,
    name: "疯癫马戏团小丑",
    core_anchor: "Twisted Circus Joker",
    broad_concept: "Fire Joker Circus Tent & Golden Joker Face Coin Show",
    allowed_entities: ["Split-Hat Court Jester", "Golden Bell Juggler", "Joker Face Gold Coin Spiller", "Circus Tent Chip Scatterer", "Vintage Carnival Spotlight Rider"],
  },
  {
    id: 55,
    name: "圣诞老人的秘密黄金工坊",
    core_anchor: "Santa Secret Gold Factory",
    broad_concept: "Santa Great Gifts Workshop & Ribbon-Wrapped Gold Bar Conveyor",
    allowed_entities: ["Snow-Bearded Santa Claus", "Gold Bar Gift Box Conveyor", "Golden Christmas Bell Operator", "Fireplace Log Cabin Workshop", "Mechanical Toy Shelf Keeper"],
  },
  {
    id: 56,
    name: "小红帽与森林狼",
    core_anchor: "Red Riding Hood Wolf",
    broad_concept: "Fairy Tale Forest Encounter & Golden Apple Basket Fortune",
    allowed_entities: ["Crimson Hooded Brave Girl", "Intelligent Grey Forest Wolf", "Golden Apple Basket Spiller", "Forest Leaf Gold Coin Path", "Misty Woodland Firefly Guide"],
    interaction_required: true,
  },
  {
    id: 57,
    name: "阿拉丁与神灯精灵",
    core_anchor: "Aladdin Magic Genie",
    broad_concept: "Arabian Lamp Smoke Treasure Cave & Persian Rug Gold Piles",
    allowed_entities: ["Purple Vest Desert Thief", "Brass Oil Lamp Genie Summoner", "Arabian Gold Coin Pile Keeper", "Jeweled Tiara Goblet Display", "Persian Rug Treasure Cave Guide"],
    interaction_required: true,
  },
  {
    id: 58,
    name: "中华美食大厨",
    core_anchor: "Chinatown Dim Sum Chef",
    broad_concept: "Culinary Art & High-Dopamine Food Festivals",
    allowed_entities: ["Jolly Chinatown Dim Sum Master", "Fiery Wok-Tossing Stir-Fry Chef", "Hot-Pot Emperor holding golden ladles", "Mystic Tea Master with flying clay teapots"],
  },
  {
    id: 59,
    name: "华夏帝王宝库",
    core_anchor: "Oriental Dynasty Emperor",
    broad_concept: "Imperial Power & Total Wealth Monopoly",
    allowed_entities: ["Regal Dynasty Emperor in Golden Dragon Robes", "First Qin Emperor holding the Imperial Jade Seal", "Imperial Golden-Armored Grand General", "Empress Dowager wearing phoenix filigree crowns"],
  },
  {
    id: 60,
    name: "星期六早晨：猫鼠大战",
    core_anchor: "Saturday Morning Slapstick Chase",
    broad_concept: "1970s Slapstick Animation & Retro Chase",
    allowed_entities: [
      "Mischievous Grey Cartoon Cat stretching paw",
      "Witty Brown Mouse holding a giant cheese slice",
      "Clumsy Bulldog wearing a spiked collar",
    ],
    interaction_required: true,
  },
  {
    id: 61,
    name: "墨西哥传统乐透卡牌",
    core_anchor: "Traditional Mexican Lotería Folk Art",
    broad_concept: "Traditional Mexican Lotería Folk Art",
    allowed_entities: [
      "Winking Celestial Sun and Crescent Moon embracing",
      "Smiling Gentleman character throwing glowing dice",
      "Singing Rooster wearing a mini sombrero",
    ],
    interaction_required: true,
  },
  {
    id: 62,
    name: "复古电视大奖赛",
    core_anchor: "Retro TV Game Show Grand Prize",
    broad_concept: "1970s Classic American TV Game Shows",
    allowed_entities: [
      "Enthusiastic Retro Show Host with long skinny microphone",
      "Excited Grandparent Contestant spinning a giant wheel",
      "Glamorous Prize Assistant opening a curtains",
    ],
    interaction_required: true,
  },
  {
    id: 63,
    name: "奶奶的温馨烘焙坊",
    core_anchor: "Grandma Cozy Baking Workshop",
    broad_concept: "Wholesome Baking & Cozy Family Comfort",
    allowed_entities: [
      "Sweet White-Haired Grandma pulling a pie from oven",
      "Playful Puppies covered in baking flour",
      "Tiny Baking Elves stacking golden cookies",
    ],
    interaction_required: true,
  },
  {
    id: 64,
    name: "乡村农场与黄金收割",
    core_anchor: "Americana Heartland Harvest Farm",
    broad_concept: "Classic Americana Heartland & Rural Farm Life",
    allowed_entities: [
      "Jolly Old Farmer driving a vintage red tractor",
      "Fluffy Sheep and Cows dancing around a hay bale",
      "Loyal Farm Dog chasing butterflies",
    ],
    interaction_required: true,
  },
  {
    id: 65,
    name: "疯狂全家福喜剧",
    core_anchor: "Satirical Retro Family Sitcom",
    broad_concept: "Satirical American Retro Family Sitcoms",
    allowed_entities: [
      "Chubby Cartoon Dad laughing hysterically",
      "Sassy Talking Family Dog holding a television remote",
      "Mischievous Toddler crawling with a giant golden key",
    ],
    interaction_required: true,
  },
  {
    id: 66,
    name: "50年代点唱机餐厅",
    core_anchor: "Jukebox Diner",
    broad_concept: "1950s Jukebox Diner & Rockabilly Nostalgia",
    market_insight:
      "这一代老年人的青春期正好撞上 1950-1960 年代的摇滚乐、霓虹点唱机和汽车餐厅（Drive-in）。这个题材对他们来说不是复古，而是他们真正的无忧青春。",
    interaction_blueprint: "溜冰鞋点餐员滑倒的滑稽瞬间 ↔ 漫天飞出的黄金奶昔与金币。",
    allowed_entities: [
      "Roller-skating Waitress balancing a giant tray",
      "Cool Retro Teenager catching a falling milkshake",
      "Animated Neon Jukebox blasting musical notes",
    ],
    interaction_required: true,
  },
  {
    id: 67,
    name: "萌宠侦探大劫案",
    core_anchor: "Pet Detective",
    broad_concept: "Cozy Mystery Pet Detectives & Cheeky Heist",
    market_insight:
      "欧美老太太是《神探夏洛克》以及各类猫狗破案小说的死忠粉。将严肃的侦探剧变成搞笑的美漫猫狗博弈，点击率极高。",
    interaction_blueprint: "沙雕巴吉度猎犬侦探拿着放大镜 ↔ 正在偷金项链的傲娇暹罗猫。",
    allowed_entities: [
      "Bumbling Basset Hound Detective with a magnifying glass",
      "Cheeky Siamese Cat Thief wearing a pearl necklace",
      "Grumpy Parrot Police Chief with a tiny badge",
    ],
    interaction_required: true,
  },
  {
    id: 68,
    name: "奇迹向日葵花园",
    core_anchor: "Sunflower Garden",
    broad_concept: "Wholesome Backyard Gardening & Miracle Crops",
    market_insight:
      "园艺（Gardening）是全美老年人投票通过最爱的退休生活。植物的自然生长与 Slots 游戏里的疯狂繁衍/长高（Growing Reels）机制天然契合。",
    interaction_blueprint: "慈祥的老爷爷浇水 ↔ 巨大的向日葵像吐钞机一样摇晃出大量金币。",
    allowed_entities: [
      "Cheerful Old Grandpa watering a massive plant",
      "Colossal Smiling Sunflower shaking down seeds",
      "Mischievous Garden Gnomes stacking gold bricks",
    ],
    interaction_required: true,
  },
  {
    id: 69,
    name: "经典棋盘游戏之夜",
    core_anchor: "Board Game Night",
    broad_concept: "Vintage Family Board Game Night",
    market_insight:
      "Monopoly（大富翁）、Scrabble（拼字）、Clue（妙探寻凶）是这代人玩了半个世纪的家庭游戏，代表着和孙子孙女享受天伦之乐的温馨符号。",
    interaction_blueprint: "巨型红色骰子滚过棋盘 ↔ 撞飞了一整座金币和筹码堆砌的城堡。",
    allowed_entities: [
      "Animated Top-Hat Token hopping across the board",
      "Pair of Giant Red Dice tumbling mid-air",
      "Excited Grandfather and Grandchild clapping hands",
    ],
    interaction_required: true,
  },
  {
    id: 70,
    name: "搞笑经典怪物夜",
    core_anchor: "Classic Monster",
    broad_concept: "Retro Hollywood Classic Monsters Slapstick",
    market_insight:
      "1930-1950年代的经典怪兽（科学怪人、德古拉、狼人）是他们童年黑白电视里的常客。把它们做成美漫《史酷比》式的搞笑闹剧，极具情怀。",
    interaction_blueprint: "笨拙的科学怪人撞翻了药水架 ↔ 飞出的绿色荧光试管与纯金古董。",
    allowed_entities: [
      "Clumsy Friendly Frankenstein dropping silver bolts",
      "Vampire Count Dracula transforming into a cute bat",
      "Playful Mummy Tangled up in golden bandages",
      "Goofy Howling Werewolf wearing a ripped flannel shirt and catching flying gold coins",
    ],
    interaction_required: true,
  },
  {
    id: 71,
    name: "墨西哥萌宠流浪乐队",
    core_anchor: "Mariachi Animals",
    broad_concept: "Festive Mexican Mariachi Animal Band",
    market_insight:
      "墨西哥及美国南部大量拉美裔老人最爱的就是传统 Mariachi 音乐。用拟人化的可爱动物来演奏，充满乐天、喜庆、大奖即将来临的多巴胺暗示。",
    interaction_blueprint: "吉他手吉娃娃高歌 ↔ 肥胖的鹦鹉在一旁疯狂摇晃沙锤飞出金币。",
    allowed_entities: [
      "Passionate Chihuahua Guitarist wearing a huge sombrero",
      "Plump Scarlet Macaw shaking shiny gold maracas",
      "Chubby Donkey playing a giant acoustic bass",
    ],
    interaction_required: true,
  },
  {
    id: 72,
    name: "嘻哈萌宠暴富队",
    core_anchor: "Hip Hop Dogs",
    broad_concept: "Streetwise Hip-Hop Pets & Urban Wealth",
    market_insight:
      "硬核街头嘻哈与极端可爱的视觉反差，在社交媒体上不分性别年龄，点击率（CTR）常年霸榜。",
    interaction_blueprint: "拽酷法斗犬戴着墨镜大笑 ↔ 踩在正在往外喷吐钻石的街头复古双卡录音机上。",
    allowed_entities: [
      "Swag French Bulldog wearing a gold chain and hoodie",
      "Sassy Persian Cat with diamond oversized sunglasses",
      "Cool Shiba Inu rocking a retro snapback cap",
    ],
    interaction_required: true,
  },
  {
    id: 73,
    name: "萌娘魔女魔法炼金坊",
    core_anchor: "Cozy Magic Witch",
    broad_concept: "Cozy Witchcraft, Crystal Alchemy & Sweet Magic",
    market_insight:
      "针对35岁+的女性休闲玩家，她们极度偏爱无害、色彩鲜艳、带点小魔法的粉紫色多巴胺题材。",
    interaction_blueprint: "Q版粉发小女巫挥舞星星魔杖 ↔ 巨大的紫色坩埚里翻滚出无数的心形粉色宝石与金币。",
    allowed_entities: [
      "Cute Pink-haired Young Witch flying on a broom",
      "Mischievous Black Cat wearing a wizard hat",
      "Floating Magical Recipe Book glowing with starlight",
    ],
    interaction_required: true,
  },
  {
    id: 74,
    name: "疯狂淘金地鼠帮",
    core_anchor: "Gopher Miner",
    broad_concept: "Frantic Animal Mining & Explosive Gold Rush",
    market_insight:
      "将传统矿工替换为满眼金光、神情疯狂的拟人化地鼠，用夸张的机械拉扯把Slots的高波动率爽感拉满。",
    interaction_blueprint: "土拨鼠操作震动着的巨大电钻 ↔ 猛烈凿开一面闪闪发光的巨型纯金矿墙。",
    allowed_entities: [
      "Manic Gopher Miner with a glowing headlamp",
      "Chubby Mole holding lit sticks of red dynamite",
      "Mechanical Drill Vehicle bursting through rocks",
    ],
    interaction_required: true,
  },
  {
    id: 75,
    name: "80年代霓虹电玩城",
    core_anchor: "Retro Arcade Neon",
    broad_concept: "1980s Retro Synthwave Arcade & Cyber Neon Casino",
    market_insight:
      "针对40-50岁的中年高净值玩家，Synthwave霓虹发光线条能天然暗示机器有极高科技的派奖算法。",
    interaction_blueprint: "复古电子像素小怪物冲出屏幕 ↔ 将满屏的2D霓虹发光casino筹码洒向玩家。",
    allowed_entities: [
      "Animated Pixel Arcade Monster jumping out of a cabinet",
      "Retro Flying Cyber-Car leaving neon light trails",
      "Glowing Holographic Casino Dealer handing out cards",
    ],
    interaction_required: true,
  },
  {
    id: 76,
    name: "华尔街肥猫私人飞机",
    core_anchor: "Fat Cat Jet",
    broad_concept: "Satirical Millionaire Animals & Luxury Jetsetters",
    market_insight:
      "用俚语Fat Cat解构资本家，躺在私人飞机里数钱的滑稽橘猫能最直白地向玩家传递暴富的心理暗示。",
    interaction_blueprint: "叼着雪茄大笑的肥胖大橘猫 ↔ 爪子一挥，私人飞机的黄金舱门打开，大叠美钞倾泻而出。",
    allowed_entities: [
      "Chubby Ginger Cat Tycoon smoking a golden cigar",
      "Sophisticated Poodle Maid pouring champagne",
      "Golden Mechanical Robot Pilot steering a luxury jet",
    ],
    interaction_required: true,
  },
  {
    id: 77,
    name: "外星怪兽疯狂实验室",
    core_anchor: "Alien Lab Mutator",
    broad_concept: "Quirky Alien Laboratory & Multiplier Mutations",
    market_insight:
      "外星人生化怪兽题材天然适合做成倍翻番（Multipliers）或合体进化的机制，美漫风黏液视觉冲击力极强。",
    interaction_blueprint: "三只眼的蓝色黏液外星小怪兽拍打按钮 ↔ 身后的巨型玻璃培养舱炸裂，飞出无数外星符文金币。",
    allowed_entities: [
      "Three-eyed Blue Jelly Alien monster laughing maniacally",
      "Mad Alien Scientist with floating green plasma beakers",
      "Giant Colossal One-eyed Monster cracking open a safe",
    ],
    interaction_required: true,
  },
  {
    id: 78,
    name: "经典宾果派对",
    core_anchor: "Bingo Hall Party",
    broad_concept: "Classic Bingo Hall Bash & Senior Social Party",
    market_insight:
      "Bingo是全美老年人社区社交生活的绝对霸主。那种手拿荧光笔涂卡并大喊BINGO的身体记忆，能瞬间给他们带来最高强度的多巴胺与安全感。",
    interaction_blueprint:
      "戴眼镜的慈祥奶奶兴奋地跳下椅子高喊BINGO ↔ 前景的玻璃摇奖机爆炸开来，飞出漫天发光的彩色宾果球和黄金硬币。",
    allowed_entities: [
      "Overjoyed Grandma waving a neon marker in celebration",
      "Jolly Grandpa checking a glowing golden bingo card",
      "Mechanical Bingo Cage exploding with multi-colored balls",
    ],
    interaction_required: true,
  },
  {
    id: 79,
    name: "老派好莱坞西部黄金列车",
    core_anchor: "Western Gold Train",
    broad_concept: "1950s Cinematic Wild West & Locomotive Heist",
    market_insight:
      "这一代银发族童年正是美国好莱坞西部片的鼎盛期。蒸汽火车、淘金热、帅气牛仔对他们来说是根深蒂固的经典爽点。",
    interaction_blueprint:
      "戴着黑色面罩和牛仔帽的浣熊劫匪奋力拉动火车闸门 ↔ 蒸汽火车车厢轰然打开，大箱的纯金金条和美钞像瀑布一样倾倒出来。",
    allowed_entities: [
      "Cheeky Bandit Raccoon pulling a giant steel lever",
      "Stern Old Town Sheriff with a shining gold star badge",
      "Vintage Iron Steam Locomotive dumping piles of gold bars",
    ],
    interaction_required: true,
  },
  {
    id: 80,
    name: "后院喂鸟器大作战",
    core_anchor: "Backyard Bird Feeder",
    broad_concept: "Wholesome Backyard Birdwatching & Squirrel Pranks",
    market_insight:
      "观鸟是北美退休老人参与度最高的庭院静修爱好。把日常跟偷吃鸟食的小松鼠斗智斗勇的温馨画面做成滑稽动画，点击率极高。",
    interaction_blueprint:
      "一只圆滚滚的胖松鼠倒挂在木质喂鸟器上偷吃 ↔ 周围一群胖乎乎的彩色红衣凤头鸟疯狂拍打翅膀，震落出漫天的金色向日葵种子与大奖硬币。",
    allowed_entities: [
      "Chubby Cardinal Bird flapping its red wings in comedic panic",
      "Mischievous Fat Squirrel raiding a wooden bird feeder",
      "Sweet Elderly Lady looking through binoculars in surprise",
    ],
    interaction_required: true,
  },
  {
    id: 81,
    name: "周日跳蚤市场淘到宝",
    core_anchor: "Flea Market Treasure",
    broad_concept: "Sunday Flea Market & Antique Treasure Hunt",
    market_insight:
      "逛车库集市和淘二手古董是美墨老人最爱的周末消遣。在尘土飞扬的旧货里翻出天价宝物的刺激感，完美映射了Slots中大奖的心理机制。",
    interaction_blueprint:
      "眼神犀利的老爷爷在旧货摊举起一个落满灰尘的黄铜怀表 ↔ 怀表魔幻般弹开，投射出巨大的发光全息时钟，四周喷涌出无数纯金首饰和复古银元。",
    allowed_entities: [
      "Sharp-eyed Grandpa holding up a dusty glowing pocket watch",
      "Smiling Grandma polishing an ornate vintage golden lamp",
      "Quirky Antique Shop Owner counting a stack of old dollar bills",
    ],
    interaction_required: true,
  },
  {
    id: 82,
    name: "猫王霓虹拉斯维加斯夜",
    core_anchor: "Elvis Retro Vegas",
    broad_concept: "1960s Classic Las Vegas Vintage Glamour",
    market_insight:
      "上世纪60-70年代的拉斯维加斯是这代人年轻时的黄金回忆。高领亮片连体服、复古霓虹招牌和老派摇滚乐对他们有着至高无上的情怀号召力。",
    interaction_blueprint:
      "一只梳着经典飞机头、身穿闪亮白色连体服的拽酷斗牛犬弹奏吉他 ↔ 音符化为霓虹光束击碎复古老虎机，纯金筹码和硬币疯狂喷涌。",
    allowed_entities: [
      "Rockabilly Bulldog wearing a glittering white rhinestone jumpsuit",
      "Glamorous Retro Showgirl fox holding massive pink feather fans",
      "Vintage Neon Las Vegas Slot Machine throwing out a cash jackpot",
    ],
    interaction_required: true,
  },
  {
    id: 83,
    name: "加勒比退休邮轮假期",
    core_anchor: "Retirement Cruise Vacation",
    broad_concept: "Tropical Retirement Cruise & Ocean Wonders",
    market_insight:
      "热带邮轮度假是欧美中产阶级老人退休生活的终极标配。椰林、躺椅、冰镇鸡尾酒代表着彻底远离劳作、享受纯粹财富赢家生活的放松心理。",
    interaction_blueprint:
      "身穿花衬衫、戴草帽的老爷爷躺在甲板长椅上喝着椰子汁 ↔ 正前方湛蓝的海面上一只巨大的海豚腾空跃起，将一个塞满金币的古老沉船宝箱顶向空中。",
    allowed_entities: [
      "Jolly Grandpa in a hibiscus Hawaiian shirt sipping a cocktail",
      "Smiling Friendly Dolphin flipping a rusty Spanish treasure chest",
      "Elegant White Cruise Ship with giant gold anchors dropping into water",
    ],
    interaction_required: true,
  },
];

export const BATCH_POSTER_THEME_BY_ID: Record<number, BatchPosterThemeCluster> = Object.fromEntries(
  BATCH_POSTER_THEME_CLUSTERS.map((cluster) => [cluster.id, cluster])
);
